---
# This playbook will install Hunspell and all the related language packs

  - name: Install Hunspell
    apt:
      pkg:
        - hunspell
        - hunspell-af
        - hunspell-en-za
        - hunspell-en-au
        - hunspell-en-ca 
        - hunspell-en-gb
        - hunspell-en-med
        - hunspell-en-us
        - hunspell-en-za
      state: latest
      update_cache: true

    - name: Append Deployment
      local_action: shell echo "* {{inventory_hostname}} (Hunspell)" >> "{{ deploy_logfile }}"
      when: result is succeeded      