# Deploy/Update trimpointdetector on the worker nodes
---
    - name: Update trimpointdetector repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        remote: "{{ repo_name }}"
        clone: yes
        update: yes
      register: result
      when: "'worker' in group_names or 'workernoexec' in group_names"

    - name: Set User
      file:
        path: "{{ repo_dest }}"
        state: directory
        owner: "{{system_user}}" 
        group: "{{system_group}}"
        recurse: yes
      when: "'worker' in group_names or 'workernoexec' in group_names"

    - name: Create log directory
      file: 
        path: "{{ repo_dest }}/logs"
        owner: "{{system_user}}"
        group: "{{system_group}}"
        mode: "u=rw,g=rw,o=rw"
        state: directory
      when: "'worker' in group_names or 'workernoexec' in group_names"

    # - name: install requirements.txt
    #   shell: pip3 install -r {{ repo_dest }}/requirements.txt
    #   when: "'worker' in group_names or 'workernoexec' in group_names"

    - name: Append Deployment
      local_action: shell echo "* {{inventory_hostname}}" >> "{{ deploy_logfile }}"
      when: result is succeeded

