# Deploy/Update emptyvenuedectector on the worker nodes
---
    - name: Update emptyvenuedectector repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        remote: "{{ repo_name }}"
        clone: yes
        update: yes
      register: result
      when: "'worker' in group_names"

    # add task to create logs folder with (opencast:opencast as owner)
    # execute pip3 install -r requirements.txt

    - name: Append Deployment
      local_action: shell echo "* {{inventory_hostname}}" >> "{{ deploy_logfile }}"
      when: result is succeeded