# Deploy/Update emptyvenuedectector on the worker nodes
---
    - name: Update emptyvenuedectector repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        remote: "{{ repo_name }}"
        clone: yes
        update: yes
      register: result
      when: "'worker' in group_names and 'workernoexec' in group_names"

    - name: Create directory
      file:
        path: /opt/VAD-python/logs
        state: directory
      when: "'worker' in group_names and 'workernoexec' in group_names"

    - name: Log file permissions
      file: path=/opt/VAD-python/logs owner=opencast group=opencast mode=0777 state=directory
      when: "'worker' in group_names and 'workernoexec' in group_names"

    - name: install requirements.txt
      shell: pip3 install -r /opt/VAD-python/requirements.txt
      when: "'worker' in group_names and 'workernoexec' in group_names"

    - name: Append Deployment
      local_action: shell echo "* {{inventory_hostname}}" >> "{{ deploy_logfile }}"
      when: result is succeeded
