---
# This playbook will install Tesseract and all the related language packs

  - name: Install Tesseract
    apt:
      pkg:
        - tesseract-ocr
        - tesseract-ocr-eng
      state: latest
      update_cache: true
    register: result      

  - name: Append Deployment
    local_action: shell echo "* {{inventory_hostname}} (Tesseract)" >> "{{ deploy_logfile }}"
    when: result is succeeded
